FROM php:7.0-cli-jessie

# TODO: try apt-get clean
RUN apt-get update && apt-get install -y git-core zip

COPY scripts/ /root/scripts
RUN /root/scripts/setup-users-paths.sh
ENV PATH=/srv/bin:${PATH}

COPY scripts/ /root/scripts
COPY --chown=elife:elife utils/ /srv/bin/
RUN /root/scripts/install-newrelic-php.sh
COPY --from=composer:1.6 /usr/bin/composer /usr/bin/composer

USER www-data
