name: build-and-push-python
on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  REPO_PREFIX: elifesciences/
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-${{ matrix.python_version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run docker buildx and push images
        run: make COMMIT=${GITHUB_SHA} REPO_PREFIX=${{ env.REGISTRY }}/${{ env.REPO_PREFIX }} buildx-and-push-python-${{ matrix.python_version }}
