name: build-and-push-php
on:
  push:
    paths:
      - '!python_image_digests.txt'
      - '!Makefile-python'
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  REPO_PREFIX: elifesciences/
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: true
    strategy:
      matrix:
        php_version: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.9.1
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run docker buildx and push images
        run: make COMMIT=${GITHUB_SHA} REPO_PREFIX=${{ env.REGISTRY }}/${{ env.REPO_PREFIX }} buildx-and-push-php-${{ matrix.php_version }}
